### ISSUE TITLE
WRF4.4.2_Install.bash assumes a wrong directory structure

### ISSUE THREAD

**Issue by rmolina** [bakamotokatas/WRF-Install-Script#5]
I tried to use `WRF4.4.2_Install.bash` on a freshly-installed Ubuntu Server 22.04.2, but it failed to compile the model.

I did a quick check, and the script assumes the WRF source directory is `./Build_WRF/WRFV${WRFversion}/`, but the tarball unpacks at  `./Build_WRF/WRF/`. It might be a recent change in the tarballs released by upstream.

As a workaround, I added a `mv WRF WRFV${WRFversion}` just before the `cd WRFV${WRFversion}` (at line 141), which worked fine.

**Comment by bakamotokatas** [comment]
Thank you very much for reporting the problem, it seems that the folder name was changed as you said, on February 3rd. I'll add the fixes tomorrow.
